@BookTracker.Api_HostAddress = http://localhost:5239
@BookTracker.Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQm9vayBUcmFja2VyIEFkbWluIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYWRtaW5AYm9va3RyYWNrZXIubG9jYWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzg0MjE2MDk5LCJpc3MiOiJCb29rVHJhY2tlciIsImF1ZCI6IkJvb2tUcmFja2VyIn0.GQ27Q0P9KICUaxiYu8df5MS3PCv1QrhBnqaPp7kKRLA
### Get Books
GET {{BookTracker.Api_HostAddress}}/books

### Get Book by Id
GET {{BookTracker.Api_HostAddress}}/books/3

### Create books
POST {{BookTracker.Api_HostAddress}}/books
Content-Type: application/json
Authorization: Bearer {{BookTracker.Token}}

{
  "title": "ikke",
  "author": "Frank Herbert",
  "year": 1965
}

### Delete Book
DELETE {{BookTracker.Api_HostAddress}}/books/2
Authorization: Bearer {{BookTracker.Token}}

### Update Book
PUT {{BookTracker.Api_HostAddress}}/books/3
Content-Type: application/json
Authorization: Bearer {{BookTracker.Token}}

{
  "title": "Changes",
  "author": "David Bowie",
  "year": 1971,
  "version": "7982e7ee-9cc4-47e2-9ab2-f608aeeb63dc"
}

### Get Books Page 1
GET {{BookTracker.Api_HostAddress}}/books?page=11&pageSize=51

### Get Books Page 2
GET {{BookTracker.Api_HostAddress}}/books?page=2&pageSize=10

### Search books
GET {{BookTracker.Api_HostAddress}}/books?search=octopus&page=6

### Search Books with paging
GET {{BookTracker.Api_HostAddress}}/books?search=octopus&page=2&pageSize=10



### Get Members Page 1
GET {{BookTracker.Api_HostAddress}}/members
Authorization: Bearer {{BookTracker.Token}}

### Get Member
GET {{BookTracker.Api_HostAddress}}/members/1
Authorization: Bearer {{BookTracker.Token}}

### Create members
POST {{BookTracker.Api_HostAddress}}/members
Content-Type: application/json

{
  "name": "Mats Cools",
  "email": "mats@dings.com",
  "password": "ValidPassword"
}

### Update member
PUT {{BookTracker.Api_HostAddress}}/members/2
Content-Type: application/json
Authorization: Bearer {{BookTracker.Token}}

{
  "name": "iemandanders",
  "email": "nie@gij.com"
}

### Delete Member
DELETE {{BookTracker.Api_HostAddress}}/members/2

### login regular member
POST {{BookTracker.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "mats@dings.com",
  "password": "ValidPassword"
}

### login Admin member
POST {{BookTracker.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "admin@booktracker.local",
  "password": "development-admin-password"
}

### current member
GET {{BookTracker.Api_HostAddress}}/auth/me
Authorization: Bearer {{BookTracker.Token}}