@BookTracker.Api_HostAddress = http://localhost:5239

### Get Books
GET {{BookTracker.Api_HostAddress}}/books

### Get Book by Id
GET {{BookTracker.Api_HostAddress}}/books/3

### Create books
POST {{BookTracker.Api_HostAddress}}/books
Content-Type: application/json

{
  "title": "ikke",
  "author": "Frank Herbert",
  "year": 1965
}

### Delete Book
DELETE {{BookTracker.Api_HostAddress}}/books/2

### Update Book
PUT {{BookTracker.Api_HostAddress}}/books/30
Content-Type: application/json

{
  "title": "Changes",
  "author": "David Bowie",
  "year": 1971
}

### Get Books Page 1
GET {{BookTracker.Api_HostAddress}}/books?page=1&pageSize=10

### Get Books Page 2
GET {{BookTracker.Api_HostAddress}}/books?page=2&pageSize=10