@BookTracker.Api_HostAddress = http://localhost:5239

### Get Books
GET {{BookTracker.Api_HostAddress}}/books


### Create books
POST {{BookTracker.Api_HostAddress}}/books
Content-Type: application/json

{
  "title": "ikke",
  "author": "Frank Herbert",
  "year": 1965
}

### Delete Book
DELETE {{BookTracker.Api_HostAddress}}/books/2
